# Generated by Django 4.2.7 on 2023-12-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_options_remove_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
    ]
