# Generated by Django 4.2.7 on 2024-01-04 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_orderitem_date_added_remove_orderitem_in_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
