# Generated by Django 4.2.7 on 2024-01-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_order_transaction_id_order_order_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
