# Generated by Django 4.2.7 on 2024-01-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('emailadd', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('streetadd', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('selected_state', models.CharField(max_length=255)),
            ],
        ),
    ]
