# Generated by Django 4.2.7 on 2024-01-15 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shipping'),
        ),
    ]
