# Generated by Django 4.2.7 on 2024-02-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_cartitem_product_name_remove_order_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='orders',
            field=models.ManyToManyField(to='core.order'),
        ),
    ]
